spring:
  datasource:
    driver-class-name: "org.postgresql.Driver"
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
    username: postgres
    password: hasan31521
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQL10Dialect"

